### ISSUE TITLE
how does this compare with connect-memcached?

### ISSUE THREAD

**Issue by jasonkarns** [leftlogic/memcached#1]

**Comment by remy** [comment]
It doesn't, it was just a clone to fix another issue. I wouldn't recommend using it - sorry!

**Comment by remy** [comment]
Oh wait, that's wrong. No, that's not what it is! But yeah, I'd not recommend it, it's entirely bespoke for jsbin.

**Comment by jasonkarns** [comment]
No worries. as connect-memcached hasn't seen much activity of late, I was looking for alternatives.
